[default]

workshop = [
    "450814997",    # CBA_A3.
    "3419106613"   # CBA_A3 addon "cache disable". Required for file patching to work.
]

file_patching = true

parameters = [
    "-noLauncher",
    "-noSplash",
    "-skipIntro",
    "-world=empty",
    "-nopause",
    "-debug",
    "-showScriptErrors"
]