name = "Infantry Only"
prefix = "infonly"
mainprefix = "z"
author = "Nimmersatt"

[version]
major = 0
minor = 1
patch = 0
build = 0

[files]
include = [
    "LICENSE",
    "logo.paa",
    "mod.cpp"
]
exclude = [
    "*.psd",
    "*.md",
    "*.sh",
    ".*" # dot files
]